[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kostas Pardalis", email = "costas.pardalis@gmail.com"},
]
dependencies = [
    "duckdb>=0.8.0",
    "pyarrow>=12.0.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}
